# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget lib_CoinUtils lib_Osi lib_clp lib_OsiClpSolver lemon flann_cpp_s vlsift aliceVision_image aliceVision_numeric aliceVision_system aliceVision_camera aliceVision_colorHarmonization aliceVision_dataio aliceVision_feature aliceVision_geometry aliceVision_graph aliceVision_gpu aliceVision_keyframe aliceVision_linearProgramming aliceVision_lInftyComputerVision aliceVision_localization aliceVision_matching aliceVision_kvld aliceVision_matchingImageCollection aliceVision_multiview aliceVision_multiview_test_data aliceVision_rig aliceVision_robustEstimation aliceVision_sensorDB aliceVision_sfm aliceVision_sfmData aliceVision_sfmDataIO aliceVision_stl aliceVision_track aliceVision_voctree aliceVision_calibration aliceVision_hdr aliceVision_lightingEstimation aliceVision_mesh aliceVision_mvsData aliceVision_mvsUtils aliceVision_fuseCut aliceVision_depthMap)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target lib_CoinUtils
add_library(lib_CoinUtils STATIC IMPORTED)

# Create imported target lib_Osi
add_library(lib_Osi STATIC IMPORTED)

# Create imported target lib_clp
add_library(lib_clp STATIC IMPORTED)

# Create imported target lib_OsiClpSolver
add_library(lib_OsiClpSolver STATIC IMPORTED)

# Create imported target lemon
add_library(lemon STATIC IMPORTED)

# Create imported target flann_cpp_s
add_library(flann_cpp_s STATIC IMPORTED)

# Create imported target vlsift
add_library(vlsift STATIC IMPORTED)

# Create imported target aliceVision_image
add_library(aliceVision_image SHARED IMPORTED)

set_target_properties(aliceVision_image PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/tmp/AliceVision_build/external/openimageio_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include/OpenEXR"
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric;/tmp/AliceVision_build/external/openimageio_build/lib64/libOpenImageIO.so;/tmp/AliceVision_build/external/openexr_build/lib/libImath-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIex-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libHalf-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIlmThread-2_3.so;dl"
)

# Create imported target aliceVision_numeric
add_library(aliceVision_numeric SHARED IMPORTED)

set_target_properties(aliceVision_numeric PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen"
)

# Create imported target aliceVision_system
add_library(aliceVision_system SHARED IMPORTED)

set_target_properties(aliceVision_system PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/tmp/AliceVision_build/external/boost_build/include"
  INTERFACE_LINK_LIBRARIES "/tmp/AliceVision_build/external/boost_build/lib/libboost_log.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_thread.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_log_setup.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_system.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_date_time.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_program_options.so"
)

# Create imported target aliceVision_camera
add_library(aliceVision_camera INTERFACE IMPORTED)

set_target_properties(aliceVision_camera PROPERTIES
  INTERFACE_LINK_LIBRARIES "aliceVision_geometry;aliceVision_multiview;aliceVision_image;aliceVision_numeric;aliceVision_stl;aliceVision_system"
)

# Create imported target aliceVision_colorHarmonization
add_library(aliceVision_colorHarmonization SHARED IMPORTED)

set_target_properties(aliceVision_colorHarmonization PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_feature;aliceVision_image;aliceVision_linearProgramming;aliceVision_matching"
)

# Create imported target aliceVision_dataio
add_library(aliceVision_dataio SHARED IMPORTED)

set_target_properties(aliceVision_dataio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_camera;aliceVision_image"
)

# Create imported target aliceVision_feature
add_library(aliceVision_feature SHARED IMPORTED)

set_target_properties(aliceVision_feature PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_image;aliceVision_numeric;aliceVision_system;aliceVision_gpu;vlsift;CCTag::CCTag;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_features2d;opencv_xfeatures2d"
)

# Create imported target aliceVision_geometry
add_library(aliceVision_geometry SHARED IMPORTED)

set_target_properties(aliceVision_geometry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric;aliceVision_linearProgramming"
)

# Create imported target aliceVision_graph
add_library(aliceVision_graph INTERFACE IMPORTED)

set_target_properties(aliceVision_graph PROPERTIES
  INTERFACE_LINK_LIBRARIES "aliceVision_system;lemon"
)

# Create imported target aliceVision_gpu
add_library(aliceVision_gpu SHARED IMPORTED)

set_target_properties(aliceVision_gpu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target aliceVision_keyframe
add_library(aliceVision_keyframe SHARED IMPORTED)

set_target_properties(aliceVision_keyframe PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/tmp/AliceVision_build/external/openimageio_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include/OpenEXR"
  INTERFACE_LINK_LIBRARIES "aliceVision_dataio;aliceVision_feature;aliceVision_voctree;/tmp/AliceVision_build/external/openimageio_build/lib64/libOpenImageIO.so;/tmp/AliceVision_build/external/openexr_build/lib/libImath-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIex-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libHalf-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIlmThread-2_3.so;dl"
)

# Create imported target aliceVision_linearProgramming
add_library(aliceVision_linearProgramming INTERFACE IMPORTED)

set_target_properties(aliceVision_linearProgramming PROPERTIES
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric;aliceVision_system;lib_clp;lib_OsiClpSolver;lib_CoinUtils;lib_Osi"
)

# Create imported target aliceVision_lInftyComputerVision
add_library(aliceVision_lInftyComputerVision SHARED IMPORTED)

set_target_properties(aliceVision_lInftyComputerVision PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_linearProgramming"
)

# Create imported target aliceVision_localization
add_library(aliceVision_localization SHARED IMPORTED)

set_target_properties(aliceVision_localization PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_camera;aliceVision_feature;aliceVision_geometry;aliceVision_image;aliceVision_matching;aliceVision_numeric;aliceVision_robustEstimation;aliceVision_sfm;aliceVision_voctree"
)

# Create imported target aliceVision_matching
add_library(aliceVision_matching SHARED IMPORTED)

set_target_properties(aliceVision_matching PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_feature;aliceVision_numeric;aliceVision_stl;aliceVision_system"
)

# Create imported target aliceVision_kvld
add_library(aliceVision_kvld SHARED IMPORTED)

set_target_properties(aliceVision_kvld PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_image;aliceVision_feature;aliceVision_numeric;aliceVision_system"
)

# Create imported target aliceVision_matchingImageCollection
add_library(aliceVision_matchingImageCollection SHARED IMPORTED)

set_target_properties(aliceVision_matchingImageCollection PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_feature;aliceVision_matching;aliceVision_multiview;aliceVision_robustEstimation;aliceVision_sfmData;/tmp/AliceVision_build/external/boost_build/lib/libboost_atomic.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_container.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_date_time.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_graph.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_log.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_log_setup.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_program_options.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_regex.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_serialization.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_system.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_thread.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_timer.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_chrono.so"
)

# Create imported target aliceVision_multiview
add_library(aliceVision_multiview SHARED IMPORTED)

set_target_properties(aliceVision_multiview PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric;aliceVision_robustEstimation;ceres;/tmp/AliceVision_build/external/suitesparse_build/lib/libspqr.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcholmod.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libccolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libamd.so;/tmp/AliceVision_build/external/lapack_build/lib64/liblapack.so;/tmp/AliceVision_build/external/lapack_build/lib64/libblas.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libsuitesparseconfig.so;/usr/lib64/librt.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libmetis.so"
)

# Create imported target aliceVision_multiview_test_data
add_library(aliceVision_multiview_test_data SHARED IMPORTED)

set_target_properties(aliceVision_multiview_test_data PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric"
)

# Create imported target aliceVision_rig
add_library(aliceVision_rig SHARED IMPORTED)

set_target_properties(aliceVision_rig PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_camera;aliceVision_geometry;aliceVision_localization;aliceVision_numeric;ceres;/tmp/AliceVision_build/external/suitesparse_build/lib/libspqr.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcholmod.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libccolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libamd.so;/tmp/AliceVision_build/external/lapack_build/lib64/liblapack.so;/tmp/AliceVision_build/external/lapack_build/lib64/libblas.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libsuitesparseconfig.so;/usr/lib64/librt.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libmetis.so;Eigen3::Eigen"
)

# Create imported target aliceVision_robustEstimation
add_library(aliceVision_robustEstimation INTERFACE IMPORTED)

set_target_properties(aliceVision_robustEstimation PROPERTIES
  INTERFACE_LINK_LIBRARIES "aliceVision_camera;aliceVision_feature;aliceVision_matching;aliceVision_numeric;aliceVision_system"
)

# Create imported target aliceVision_sensorDB
add_library(aliceVision_sensorDB SHARED IMPORTED)

set_target_properties(aliceVision_sensorDB PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target aliceVision_sfm
add_library(aliceVision_sfm SHARED IMPORTED)

set_target_properties(aliceVision_sfm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_system;aliceVision_numeric;aliceVision_multiview;aliceVision_geometry;aliceVision_camera;aliceVision_matching;aliceVision_feature;aliceVision_graph;aliceVision_track;aliceVision_lInftyComputerVision;aliceVision_linearProgramming;aliceVision_sfmData;aliceVision_sfmDataIO;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so;ceres;/tmp/AliceVision_build/external/suitesparse_build/lib/libspqr.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcholmod.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libccolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libcolamd.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libamd.so;/tmp/AliceVision_build/external/lapack_build/lib64/liblapack.so;/tmp/AliceVision_build/external/lapack_build/lib64/libblas.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libsuitesparseconfig.so;/usr/lib64/librt.so;/tmp/AliceVision_build/external/suitesparse_build/lib/libmetis.so"
)

# Create imported target aliceVision_sfmData
add_library(aliceVision_sfmData SHARED IMPORTED)

set_target_properties(aliceVision_sfmData PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_system;aliceVision_numeric;aliceVision_image;aliceVision_feature;aliceVision_geometry;aliceVision_camera;aliceVision_stl;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so"
)

# Create imported target aliceVision_sfmDataIO
add_library(aliceVision_sfmDataIO SHARED IMPORTED)

set_target_properties(aliceVision_sfmDataIO PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_sfmData;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so"
)

# Create imported target aliceVision_stl
add_library(aliceVision_stl INTERFACE IMPORTED)

set_target_properties(aliceVision_stl PROPERTIES
  INTERFACE_LINK_LIBRARIES "/tmp/AliceVision_build/external/boost_build/lib/libboost_container.so"
)

# Create imported target aliceVision_track
add_library(aliceVision_track SHARED IMPORTED)

set_target_properties(aliceVision_track PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_feature;aliceVision_matching;aliceVision_stl;lemon"
)

# Create imported target aliceVision_voctree
add_library(aliceVision_voctree SHARED IMPORTED)

set_target_properties(aliceVision_voctree PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_feature;aliceVision_sfmData;aliceVision_system;Eigen3::Eigen"
)

# Create imported target aliceVision_calibration
add_library(aliceVision_calibration SHARED IMPORTED)

set_target_properties(aliceVision_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_features2d;opencv_xfeatures2d"
)

# Create imported target aliceVision_hdr
add_library(aliceVision_hdr SHARED IMPORTED)

set_target_properties(aliceVision_hdr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target aliceVision_lightingEstimation
add_library(aliceVision_lightingEstimation SHARED IMPORTED)

set_target_properties(aliceVision_lightingEstimation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_image;aliceVision_system;Eigen3::Eigen"
)

# Create imported target aliceVision_mesh
add_library(aliceVision_mesh SHARED IMPORTED)

set_target_properties(aliceVision_mesh PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_mvsData;aliceVision_mvsUtils;Geogram::geogram;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so"
)

# Create imported target aliceVision_mvsData
add_library(aliceVision_mvsData SHARED IMPORTED)

set_target_properties(aliceVision_mvsData PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/tmp/AliceVision_build/external/zlib_build/include;/tmp/AliceVision_build/external/boost_build/include;/tmp/AliceVision_build/external/openimageio_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include;/tmp/AliceVision_build/external/openexr_build/include/OpenEXR"
  INTERFACE_LINK_LIBRARIES "aliceVision_system;/tmp/AliceVision_build/external/zlib_build/lib/libz.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so;/tmp/AliceVision_build/external/openimageio_build/lib64/libOpenImageIO.so;/tmp/AliceVision_build/external/openexr_build/lib/libImath-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIex-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libHalf-2_3.so;/tmp/AliceVision_build/external/openexr_build/lib/libIlmThread-2_3.so;dl"
)

# Create imported target aliceVision_mvsUtils
add_library(aliceVision_mvsUtils SHARED IMPORTED)

set_target_properties(aliceVision_mvsUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_numeric;aliceVision_multiview;aliceVision_mvsData;aliceVision_sfmData"
)

# Create imported target aliceVision_fuseCut
add_library(aliceVision_fuseCut SHARED IMPORTED)

set_target_properties(aliceVision_fuseCut PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "aliceVision_mvsData;aliceVision_mvsUtils;aliceVision_mesh;aliceVision_system;Geogram::geogram;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_graph.so;/tmp/AliceVision_build/external/boost_build/lib/libboost_container.so"
)

# Create imported target aliceVision_depthMap
add_library(aliceVision_depthMap SHARED IMPORTED)

set_target_properties(aliceVision_depthMap PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/usr/local/cuda/include"
  INTERFACE_LINK_LIBRARIES "/usr/local/cuda/lib64/libcudart.so;/usr/local/cuda/lib64/libcudadevrt.a;aliceVision_mvsData;aliceVision_mvsUtils;aliceVision_system;/tmp/AliceVision_build/external/boost_build/lib/libboost_filesystem.so;/usr/local/cuda/lib64/libcudadevrt.a;/usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a;aliceVision_gpu;aliceVision_sfmData;aliceVision_sfmDataIO"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/AliceVisionTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
